NálezníkASP/Controllers/FindingController.cs
using Microsoft.AspNetCore.Mvc;
using NálezníkASP.Services;
using NálezníkASP.DTO;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using NálezníkASP.Models;
using System.Globalization;

namespace NálezníkASP.Controllers {
	[Authorize]
	public class FindingController : Controller {
		private FindingService findingService;
		private UserManager<AppUser> userManager;
		CultureInfo culture = new CultureInfo("en-US");

		public FindingController(FindingService findingService, UserManager<AppUser> userManager) {
			this.findingService = findingService;
			this.userManager = userManager;
		}

		[Authorize]
		[HttpGet]
		public IActionResult Index() {
			return View();
		}

		public async Task<IActionResult> SaveAsync(FindingDto finding, string sourceView) {
			var user = await userManager.GetUserAsync(HttpContext.User);
			finding.Username = user.UserName;
			if (ModelState.IsValid) {
				bool IsCoin = false;
				if (sourceView == "Coin") {
					IsCoin = true;
				}
				await findingService.SaveFindingAsync(finding, user, IsCoin);
				return RedirectToAction("Index");
			}
			var errors = ModelState.Values.SelectMany(x => x.Errors).Select(x => x.ErrorMessage).ToList();
			ViewData["ValidationErrors"] = errors;

			return sourceView == "coin" ? View("NewCoin") : View("NewArtifact");
		}
		[HttpGet]
		[Authorize]
		public IActionResult NewCoin() {
			return View();
		}

		[HttpGet]
		[Authorize]
		public IActionResult NewArtifact() {
			return View();
		}
		[HttpGet]
		[Authorize]
		public async Task<IActionResult> MyFindingsAsync(string filterType, string filterName) {
			var user = await userManager.GetUserAsync(HttpContext.User);
			if (string.IsNullOrEmpty(filterName) && (string.IsNullOrEmpty(filterType))) {
				var allFindings = await findingService.GetAllFindings(user);
				return View(allFindings);
			}
			else {
				var filteredFindings = findingService.GetFilteredFindigns(user, filterType, filterName);
				return View(filteredFindings);
			}
		}
		[HttpPost]
		public async Task<IActionResult> Delete(int id) {
			var user = await userManager.GetUserAsync(HttpContext.User);
			var subjectToDelete = await findingService.GetByIdAsync(id, user);
			if (subjectToDelete == null) {
				return View("NotFound");
			}
			await findingService.DeleteAsync(id);
			return RedirectToAction("MyFindings");
		}
		[HttpPost]
		public async Task<IActionResult> DeleteAdmin(int id) {
			await findingService.DeleteAsync(id);
			return RedirectToAction("AllFindings");
		}

		[HttpGet]
		[Authorize]
		public async Task<IActionResult> EditAsync(int id) {
			var user = await userManager.GetUserAsync(HttpContext.User);
			var finding = await findingService.GetByIdAsync(id, user);
			if (finding == null) {
				return View("NotFound");
			}

			return View(finding);
		}
		[HttpPost]
		public async Task<IActionResult> EditAsync(int id, FindingDto finding, string sourceView) {

			var user = await userManager.GetUserAsync(HttpContext.User);
			await findingService.UpdateAsync(id, finding, user, finding.Coin);
			return RedirectToAction("MyFindings");
		}
		[HttpGet]
		[Authorize]
		public async Task<IActionResult> MapOfFindingsAsync() {
			var user = await userManager.GetUserAsync(HttpContext.User);
			var allFindings = await findingService.GetAllFindings(user);
			return View(allFindings);
		}
		[HttpGet]
		public async Task<IActionResult> Detail(int id) {
			var finding = await findingService.GetByIdWithoutUserAsync(id);
			if (finding == null) {
				return View("NotFound");
			}
			return View(finding);
		}
		[HttpGet]
		[Authorize]
		public async Task<IActionResult> AllFindingsAsync(string filterName, string filterNameUser, string filterType) {
			if (string.IsNullOrEmpty(filterName) && (string.IsNullOrEmpty(filterType) && (string.IsNullOrEmpty(filterNameUser)))) {
				var allFindings = await findingService.GetAllFindings();
				return View(allFindings);
			}
			else {
				var filteredFindings = findingService.GetFilteredFindigns(filterName, filterNameUser, filterType);
				return View(filteredFindings);
			}
		}

	}

}

NálezníkASP/Controllers/ProfileController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using NálezníkASP.DTO;
using NálezníkASP.Models;
using NálezníkASP.Services;

namespace NálezníkASP.Controllers {
    [Authorize]
    public class ProfileController : Controller {
        private Microsoft.AspNetCore.Identity.UserManager<AppUser> userManager;
        private ProfileService profileService;

        public ProfileController(ProfileService profileService, UserManager<AppUser> userManager) {
            this.profileService = profileService;
            this.userManager = userManager;
        }
        public async Task<IActionResult> IndexAsync() {
            var user = await userManager.GetUserAsync(HttpContext.User);
            var ProfileData = await profileService.GetProfileData(user);
            return View(ProfileData);
        }

        [HttpGet]
        public async Task<IActionResult> EditAsync() {
            var user = await userManager.GetUserAsync(HttpContext.User);
            var ProfileData = await profileService.GetProfileData(user);
            return View(ProfileData);
        }

        [HttpPost]
        public async Task<IActionResult> Index(IFormFile profilePicture) {
            if (profilePicture != null) {
                var user = await userManager.GetUserAsync(HttpContext.User);
                await profileService.UpdateProfilePicture(user, profilePicture);
                return RedirectToAction("Index");
            }
                return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> SaveProfileChanges(ProfileDto profile) {
            var user = await userManager.GetUserAsync(HttpContext.User);
            await profileService.UpdateProfile(profile,user);
            return RedirectToAction("Index");
        }
        [HttpGet]
        [Route("Profile/ProfileReview/{Username}")]
        public async Task<IActionResult> ProfileReview(string Username) {
            var userProfile = await profileService.GetUserProfileReview(Username);
            
            return View(userProfile);
        }

    }
}

NálezníkASP/Controllers/RolesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using NálezníkASP.Models;

namespace NálezníkASP.Controllers {
    [Authorize(Roles = "Implementor")]
    public class RolesController : Controller {
        private RoleManager<IdentityRole> roleManager;
        private UserManager<AppUser> userManager;
        public RolesController(RoleManager<IdentityRole> roleManager, UserManager<AppUser> userManager) {
            this.roleManager = roleManager;
            this.userManager = userManager;
        }

        [Authorize(Roles = "Implementor")]
        public IActionResult Index() {
            return View(roleManager.Roles);
        }

        public IActionResult Create() => View();

        [HttpPost]
        public async Task<IActionResult> Create(string name) {
            IdentityResult result = await roleManager.CreateAsync(new IdentityRole(name));
            if (result.Succeeded) {
                return RedirectToAction("Index");
            }
            else {
                foreach (var error in result.Errors) {
                    ModelState.AddModelError("", error.Description);
                }
                return View(name);
            }
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id) {
            IdentityRole foundRole = await roleManager.FindByIdAsync(id);
            if (foundRole != null) {
                IdentityResult delete = await roleManager.DeleteAsync(foundRole);
                if (delete.Succeeded) {
                    return RedirectToAction("Index");
                }
                else {
                    foreach (var error in delete.Errors) {
                        ModelState.AddModelError("", error.Description);
                    }
                }
            }
            else {
                ModelState.AddModelError("", "No role found");
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Edit(string id) {
            IdentityRole roleToEdit = await roleManager.FindByIdAsync(id);
            List<AppUser> members = new List<AppUser>();
            List<AppUser> nonmembers = new List<AppUser>();
            if (roleToEdit != null) {
                foreach (AppUser user in userManager.Users) {
                    var list = await userManager.IsInRoleAsync(user, roleToEdit.Name) ? members : nonmembers;
                    list.Add(user);
                }
                return View(new RoleEdit {
                    Role = roleToEdit,
                    Members = members,
                    nonMembers = nonmembers
                });
            }
            else {
                ModelState.AddModelError("", "Chyba");
                return View();
            }
        }
        [HttpPost]
        public async Task<IActionResult> Edit(RoleModification modification) {
            foreach (string userID in modification.AddIds) {
                AppUser user = await userManager.FindByIdAsync(userID);
                if (user != null) {
                    IdentityResult result = await userManager.AddToRoleAsync(user, modification.RoleName);
                    if (!result.Succeeded) {
                        AddModelErrors(result);
                    }

                }
            }
            foreach (string userId in modification.DeleteIds ?? Array.Empty<String>()) {
                AppUser user = await userManager.FindByIdAsync(userId);
                if (user != null) {
                    IdentityResult result = await userManager.RemoveFromRoleAsync(user, modification.RoleName);
                    if (result.Succeeded) {
                        AddModelErrors(result);
                    }
                }
            }
            return RedirectToAction("Index");
        }

        private void AddModelErrors(IdentityResult result) {
            foreach (var error in result.Errors) {
                ModelState.AddModelError("", error.Description);
            }
        }
    }
}

NálezníkASP/Controllers/UsersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using NálezníkASP.DTO;
using NálezníkASP.Models;

namespace NálezníkASP.Controllers {
    [Authorize(Roles = "Implementor,UserManager")]
    public class UsersController : Controller {
        private UserManager<AppUser> userManager;
        private IPasswordHasher<AppUser> passwordHasher;


        public UsersController(UserManager<AppUser> userManager, IPasswordHasher<AppUser> passwordHasher) {
            this.userManager = userManager;
            this.passwordHasher = passwordHasher;
        }
        [Authorize (Roles = "Implementor,UserManager")]
        public IActionResult Index() {
            return View(userManager.Users);
        }

        //public IActionResult Create() {
        //    return View();
        //}

        //[HttpPost]
        //public async Task<IActionResult> CreateAsync(UserDto newUser) {
        //    if (ModelState.IsValid) {
        //        AppUser appUser = new AppUser() {
        //            Email = newUser.Email,
        //            UserName = newUser.Name,
        //        };
        //        IdentityResult identityResult = await userManager.CreateAsync(appUser, newUser.Password);
        //        if (identityResult.Succeeded) {
        //            return RedirectToAction("Index");
        //        }
        //        else {
        //            foreach (IdentityError error in identityResult.Errors) {
        //                ModelState.AddModelError(string.Empty, error.Description);
        //            }
        //        }

        //    }
        //    return View(newUser);

        //}

        public async Task<IActionResult> Edit(string id) {
            var appUser = await userManager.FindByIdAsync(id);
            if (appUser == null) {
                return View("NotFound");
            }
            else {
                return View(appUser);
            }
        }
        [HttpPost]
        public async Task<IActionResult> Edit(string Id, string Email, string password) {
            AppUser userToEdit = await userManager.FindByIdAsync(Id);
            if (userToEdit != null) {
                userToEdit.Email = Email;
                userToEdit.PasswordHash = passwordHasher.HashPassword(userToEdit, password);
                IdentityResult result = await userManager.UpdateAsync(userToEdit);
                if (result.Succeeded) {
                    return RedirectToAction("Index");
                }
                else {
                    foreach (IdentityError error in result.Errors)
                        ModelState.AddModelError(string.Empty, error.Description);
                }
            }
            else {
                ModelState.AddModelError("", "User not found.");
            }
            return View(userToEdit);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id) {
            AppUser appUser = await userManager.FindByIdAsync(id);
            if (appUser != null) {
                IdentityResult result = await userManager.DeleteAsync(appUser);
                if (result.Succeeded) {
                    return RedirectToAction("Index");
                }
                else {
                    foreach (IdentityError error in result.Errors) {
                        ModelState.AddModelError("", error.Description);
                    }
                }
            }
            else {
                ModelState.AddModelError("", "User not found");
            }
            return RedirectToAction("Index");
        }


    }


}

NálezníkASP/Views/Shared/AccessDenied.cshtml
<h1>Access Denied!</h1>

NálezníkASP/Views/Shared/NotFound.cshtml
@{
    ViewData["Title"] = "Page Not Found";
}

<div class="text-center">
    <img src="/images/error404.png" alt="404 Error Image" class="img-fluid" />
    <p class="mt-3 text-black font-weight-bold" style="font-size: 18px;">
        Oops! Looks like you find junior programmer page...<br />
        Error 404: Page not found.
    </p>
</div>

NálezníkASP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - Nálezník</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/NálezníkASP.styles.css" asp-append-version="true" />
	<link rel="icon" type="image/x-icon" href="~/images/favicon16.png" />
	<link rel="stylesheet" href="https://unpkg.com/leaflet/dist/leaflet.css" />
	<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">
	<script src="https://unpkg.com/leaflet/dist/leaflet.js"></script>
</head>
<body style="background-color: #d3d3d3;">
	<header>
		<nav class="navbar navbar-expand-lg navbar-light bg-light shadow-sm">
			<div class="container-fluid">
				<a class="navbar-brand fw-bold" asp-area="" asp-controller="Home" asp-action="Index" style="color: #333;">
					Nálezník
				</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
						aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>

				@if (User.Identity.IsAuthenticated) {
					<div class="collapse navbar-collapse" id="navbarNav">
						<ul class="navbar-nav ms-auto">

							<li class="nav-item">
								<a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">
									<i class="bi bi-house-door"></i> Home
								</a>
							</li>
							<li class="nav-item">
								<a class="nav-link" asp-area="" asp-controller="Dashboard" asp-action="Index">
									<i class="bi bi-grid-3x3-gap"></i> Dashboard
								</a>
							</li>
							<li class="nav-item">
								<a class="nav-link" asp-area="" asp-controller="Home" asp-action="Information">
									<i class="bi bi-info-circle"></i> Information
								</a>
							</li>
							<li class="nav-item">
								<a class="nav-link" asp-area="" asp-controller="Profile" asp-action="Index">
									<i class="bi bi-person-circle"></i> My Profile
								</a>
							</li>

							<li class="nav-item">
								<a class="nav-link" asp-area="" asp-controller="Finding" asp-action="Index">
									<i class="bi bi-plus-circle"></i> New Finding
								</a>
							</li>
							<li class="nav-item">
								<a class="nav-link" asp-area="" asp-controller="Finding" asp-action="MyFindings">
									<i class="bi bi-folder"></i> My Findings
								</a>
							</li>
							<li class="nav-item">
								<a class="nav-link" asp-area="" asp-controller="Finding" asp-action="MapOfFindings">
									<i class="bi bi-map"></i> Map of Findings
								</a>
							</li>
							<div class="navbar-divider"></div>
							<li class="nav-item dropdown">
								<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
									<i class="bi bi-globe-americas"></i> Other users
								</a>
								<ul class="dropdown-menu" aria-labelledby="navbarDropdown">
									<li>
										<a class="dropdown-item" asp-area="" asp-controller="Finding" asp-action="AllFindings">
											<i class="bi bi-folder"></i> All findings
										</a>
									</li>
										@* <li>
											<a class="dropdown-item" asp-area="" asp-controller="Finding" asp-action="MyFindings">
											<i class="bi bi-map"></i> Map of all findings
											</a>
										</li> *@ 
								</ul>
							</li>
							@if (User.IsInRole("Implementor") || User.IsInRole("UserManager")) {
								<div class="navbar-divider"></div>
								<li class="nav-item dropdown">
									<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
										<i class="bi bi-person-lines-fill"></i> Admin
									</a>
									<ul class="dropdown-menu" aria-labelledby="navbarDropdown">
										<li>
											<a class="dropdown-item" asp-area="" asp-controller="Users" asp-action="Index">
												<i class="bi bi-person-lines-fill"></i> Users
											</a>
										</li>
										@if (User.IsInRole("Implementor")){
											<li>
												<a class="dropdown-item" asp-area="" asp-controller="Roles" asp-action="Index">
													<i class="bi bi-shield-lock"></i> Roles
												</a>
											</li>
											}
										</ul>
									</li>
								}

							</ul>
						</div>
					}
				</div>
			</nav>
		</header>

		<div class="container">
			<main role="main" class="pb-3">
				@RenderBody()
			</main>
		</div>

		<footer class="border-top footer text-muted">
			<div class="container">
				&copy; 2024 - Nálezník - Daniel Vašut
			</div>
		</footer>
		<script src="~/lib/jquery/dist/jquery.min.js"></script>
		<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
		<script src="~/js/site.js" asp-append-version="true"></script>
		@await RenderSectionAsync("Scripts", required: false)
	</body>
	</html>